// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package top.fengye.rpc.grpc;

public final class Grpc {
  private Grpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppendEntriesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.fengye.rpc.grpc.AppendEntriesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
     * @return Whether the command field is set.
     */
    boolean hasCommand();
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
     * @return The command.
     */
    top.fengye.rpc.grpc.BizParam.Command getCommand();
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
     */
    top.fengye.rpc.grpc.BizParam.CommandOrBuilder getCommandOrBuilder();
  }
  /**
   * Protobuf type {@code top.fengye.rpc.grpc.AppendEntriesRequest}
   */
  public static final class AppendEntriesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.fengye.rpc.grpc.AppendEntriesRequest)
      AppendEntriesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppendEntriesRequest.newBuilder() to construct.
    private AppendEntriesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesRequest() {
      nodeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppendEntriesRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fengye.rpc.grpc.Grpc.AppendEntriesRequest.class, top.fengye.rpc.grpc.Grpc.AppendEntriesRequest.Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMAND_FIELD_NUMBER = 2;
    private top.fengye.rpc.grpc.BizParam.Command command_;
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
     * @return Whether the command field is set.
     */
    @java.lang.Override
    public boolean hasCommand() {
      return command_ != null;
    }
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
     * @return The command.
     */
    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.Command getCommand() {
      return command_ == null ? top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance() : command_;
    }
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
     */
    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.CommandOrBuilder getCommandOrBuilder() {
      return command_ == null ? top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance() : command_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
      }
      if (command_ != null) {
        output.writeMessage(2, getCommand());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
      }
      if (command_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCommand());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.fengye.rpc.grpc.Grpc.AppendEntriesRequest)) {
        return super.equals(obj);
      }
      top.fengye.rpc.grpc.Grpc.AppendEntriesRequest other = (top.fengye.rpc.grpc.Grpc.AppendEntriesRequest) obj;

      if (!getNodeId()
          .equals(other.getNodeId())) return false;
      if (hasCommand() != other.hasCommand()) return false;
      if (hasCommand()) {
        if (!getCommand()
            .equals(other.getCommand())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      if (hasCommand()) {
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getCommand().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.fengye.rpc.grpc.Grpc.AppendEntriesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.fengye.rpc.grpc.AppendEntriesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.fengye.rpc.grpc.AppendEntriesRequest)
        top.fengye.rpc.grpc.Grpc.AppendEntriesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.fengye.rpc.grpc.Grpc.AppendEntriesRequest.class, top.fengye.rpc.grpc.Grpc.AppendEntriesRequest.Builder.class);
      }

      // Construct using top.fengye.rpc.grpc.Grpc.AppendEntriesRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = "";
        command_ = null;
        if (commandBuilder_ != null) {
          commandBuilder_.dispose();
          commandBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_descriptor;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.AppendEntriesRequest getDefaultInstanceForType() {
        return top.fengye.rpc.grpc.Grpc.AppendEntriesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.AppendEntriesRequest build() {
        top.fengye.rpc.grpc.Grpc.AppendEntriesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.AppendEntriesRequest buildPartial() {
        top.fengye.rpc.grpc.Grpc.AppendEntriesRequest result = new top.fengye.rpc.grpc.Grpc.AppendEntriesRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.fengye.rpc.grpc.Grpc.AppendEntriesRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.command_ = commandBuilder_ == null
              ? command_
              : commandBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.fengye.rpc.grpc.Grpc.AppendEntriesRequest) {
          return mergeFrom((top.fengye.rpc.grpc.Grpc.AppendEntriesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.fengye.rpc.grpc.Grpc.AppendEntriesRequest other) {
        if (other == top.fengye.rpc.grpc.Grpc.AppendEntriesRequest.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasCommand()) {
          mergeCommand(other.getCommand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getCommandFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 1;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private top.fengye.rpc.grpc.BizParam.Command command_;
      private com.google.protobuf.SingleFieldBuilderV3<
          top.fengye.rpc.grpc.BizParam.Command, top.fengye.rpc.grpc.BizParam.Command.Builder, top.fengye.rpc.grpc.BizParam.CommandOrBuilder> commandBuilder_;
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       * @return Whether the command field is set.
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       * @return The command.
       */
      public top.fengye.rpc.grpc.BizParam.Command getCommand() {
        if (commandBuilder_ == null) {
          return command_ == null ? top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance() : command_;
        } else {
          return commandBuilder_.getMessage();
        }
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       */
      public Builder setCommand(top.fengye.rpc.grpc.BizParam.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
        } else {
          commandBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       */
      public Builder setCommand(
          top.fengye.rpc.grpc.BizParam.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          command_ = builderForValue.build();
        } else {
          commandBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       */
      public Builder mergeCommand(top.fengye.rpc.grpc.BizParam.Command value) {
        if (commandBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            command_ != null &&
            command_ != top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance()) {
            getCommandBuilder().mergeFrom(value);
          } else {
            command_ = value;
          }
        } else {
          commandBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = null;
        if (commandBuilder_ != null) {
          commandBuilder_.dispose();
          commandBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       */
      public top.fengye.rpc.grpc.BizParam.Command.Builder getCommandBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       */
      public top.fengye.rpc.grpc.BizParam.CommandOrBuilder getCommandOrBuilder() {
        if (commandBuilder_ != null) {
          return commandBuilder_.getMessageOrBuilder();
        } else {
          return command_ == null ?
              top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance() : command_;
        }
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.fengye.rpc.grpc.BizParam.Command, top.fengye.rpc.grpc.BizParam.Command.Builder, top.fengye.rpc.grpc.BizParam.CommandOrBuilder> 
          getCommandFieldBuilder() {
        if (commandBuilder_ == null) {
          commandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.fengye.rpc.grpc.BizParam.Command, top.fengye.rpc.grpc.BizParam.Command.Builder, top.fengye.rpc.grpc.BizParam.CommandOrBuilder>(
                  getCommand(),
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        return commandBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.fengye.rpc.grpc.AppendEntriesRequest)
    }

    // @@protoc_insertion_point(class_scope:top.fengye.rpc.grpc.AppendEntriesRequest)
    private static final top.fengye.rpc.grpc.Grpc.AppendEntriesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.fengye.rpc.grpc.Grpc.AppendEntriesRequest();
    }

    public static top.fengye.rpc.grpc.Grpc.AppendEntriesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppendEntriesRequest>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesRequest>() {
      @java.lang.Override
      public AppendEntriesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.fengye.rpc.grpc.Grpc.AppendEntriesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppendEntriesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.fengye.rpc.grpc.AppendEntriesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();
  }
  /**
   * Protobuf type {@code top.fengye.rpc.grpc.AppendEntriesResponse}
   */
  public static final class AppendEntriesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.fengye.rpc.grpc.AppendEntriesResponse)
      AppendEntriesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppendEntriesResponse.newBuilder() to construct.
    private AppendEntriesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesResponse() {
      nodeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppendEntriesResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fengye.rpc.grpc.Grpc.AppendEntriesResponse.class, top.fengye.rpc.grpc.Grpc.AppendEntriesResponse.Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.fengye.rpc.grpc.Grpc.AppendEntriesResponse)) {
        return super.equals(obj);
      }
      top.fengye.rpc.grpc.Grpc.AppendEntriesResponse other = (top.fengye.rpc.grpc.Grpc.AppendEntriesResponse) obj;

      if (!getNodeId()
          .equals(other.getNodeId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.fengye.rpc.grpc.Grpc.AppendEntriesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.fengye.rpc.grpc.AppendEntriesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.fengye.rpc.grpc.AppendEntriesResponse)
        top.fengye.rpc.grpc.Grpc.AppendEntriesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.fengye.rpc.grpc.Grpc.AppendEntriesResponse.class, top.fengye.rpc.grpc.Grpc.AppendEntriesResponse.Builder.class);
      }

      // Construct using top.fengye.rpc.grpc.Grpc.AppendEntriesResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_descriptor;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.AppendEntriesResponse getDefaultInstanceForType() {
        return top.fengye.rpc.grpc.Grpc.AppendEntriesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.AppendEntriesResponse build() {
        top.fengye.rpc.grpc.Grpc.AppendEntriesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.AppendEntriesResponse buildPartial() {
        top.fengye.rpc.grpc.Grpc.AppendEntriesResponse result = new top.fengye.rpc.grpc.Grpc.AppendEntriesResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.fengye.rpc.grpc.Grpc.AppendEntriesResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.fengye.rpc.grpc.Grpc.AppendEntriesResponse) {
          return mergeFrom((top.fengye.rpc.grpc.Grpc.AppendEntriesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.fengye.rpc.grpc.Grpc.AppendEntriesResponse other) {
        if (other == top.fengye.rpc.grpc.Grpc.AppendEntriesResponse.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 1;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.fengye.rpc.grpc.AppendEntriesResponse)
    }

    // @@protoc_insertion_point(class_scope:top.fengye.rpc.grpc.AppendEntriesResponse)
    private static final top.fengye.rpc.grpc.Grpc.AppendEntriesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.fengye.rpc.grpc.Grpc.AppendEntriesResponse();
    }

    public static top.fengye.rpc.grpc.Grpc.AppendEntriesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppendEntriesResponse>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesResponse>() {
      @java.lang.Override
      public AppendEntriesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.fengye.rpc.grpc.Grpc.AppendEntriesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApplyVoteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.fengye.rpc.grpc.ApplyVoteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    long getTerm();
  }
  /**
   * Protobuf type {@code top.fengye.rpc.grpc.ApplyVoteRequest}
   */
  public static final class ApplyVoteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.fengye.rpc.grpc.ApplyVoteRequest)
      ApplyVoteRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplyVoteRequest.newBuilder() to construct.
    private ApplyVoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplyVoteRequest() {
      nodeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ApplyVoteRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fengye.rpc.grpc.Grpc.ApplyVoteRequest.class, top.fengye.rpc.grpc.Grpc.ApplyVoteRequest.Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TERM_FIELD_NUMBER = 2;
    private long term_ = 0L;
    /**
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
      }
      if (term_ != 0L) {
        output.writeInt64(2, term_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
      }
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, term_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.fengye.rpc.grpc.Grpc.ApplyVoteRequest)) {
        return super.equals(obj);
      }
      top.fengye.rpc.grpc.Grpc.ApplyVoteRequest other = (top.fengye.rpc.grpc.Grpc.ApplyVoteRequest) obj;

      if (!getNodeId()
          .equals(other.getNodeId())) return false;
      if (getTerm()
          != other.getTerm()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.fengye.rpc.grpc.Grpc.ApplyVoteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.fengye.rpc.grpc.ApplyVoteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.fengye.rpc.grpc.ApplyVoteRequest)
        top.fengye.rpc.grpc.Grpc.ApplyVoteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.fengye.rpc.grpc.Grpc.ApplyVoteRequest.class, top.fengye.rpc.grpc.Grpc.ApplyVoteRequest.Builder.class);
      }

      // Construct using top.fengye.rpc.grpc.Grpc.ApplyVoteRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = "";
        term_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_descriptor;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.ApplyVoteRequest getDefaultInstanceForType() {
        return top.fengye.rpc.grpc.Grpc.ApplyVoteRequest.getDefaultInstance();
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.ApplyVoteRequest build() {
        top.fengye.rpc.grpc.Grpc.ApplyVoteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.ApplyVoteRequest buildPartial() {
        top.fengye.rpc.grpc.Grpc.ApplyVoteRequest result = new top.fengye.rpc.grpc.Grpc.ApplyVoteRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.fengye.rpc.grpc.Grpc.ApplyVoteRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.term_ = term_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.fengye.rpc.grpc.Grpc.ApplyVoteRequest) {
          return mergeFrom((top.fengye.rpc.grpc.Grpc.ApplyVoteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.fengye.rpc.grpc.Grpc.ApplyVoteRequest other) {
        if (other == top.fengye.rpc.grpc.Grpc.ApplyVoteRequest.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                term_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 1;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long term_ ;
      /**
       * <code>int64 term = 2;</code>
       * @return The term.
       */
      @java.lang.Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>int64 term = 2;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 term = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        term_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.fengye.rpc.grpc.ApplyVoteRequest)
    }

    // @@protoc_insertion_point(class_scope:top.fengye.rpc.grpc.ApplyVoteRequest)
    private static final top.fengye.rpc.grpc.Grpc.ApplyVoteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.fengye.rpc.grpc.Grpc.ApplyVoteRequest();
    }

    public static top.fengye.rpc.grpc.Grpc.ApplyVoteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplyVoteRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApplyVoteRequest>() {
      @java.lang.Override
      public ApplyVoteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApplyVoteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApplyVoteRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.fengye.rpc.grpc.Grpc.ApplyVoteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApplyVoteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.fengye.rpc.grpc.ApplyVoteResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    java.lang.String getNodeId();
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    /**
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <code>bool agreed = 3;</code>
     * @return The agreed.
     */
    boolean getAgreed();
  }
  /**
   * Protobuf type {@code top.fengye.rpc.grpc.ApplyVoteResponse}
   */
  public static final class ApplyVoteResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.fengye.rpc.grpc.ApplyVoteResponse)
      ApplyVoteResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplyVoteResponse.newBuilder() to construct.
    private ApplyVoteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplyVoteResponse() {
      nodeId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ApplyVoteResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fengye.rpc.grpc.Grpc.ApplyVoteResponse.class, top.fengye.rpc.grpc.Grpc.ApplyVoteResponse.Builder.class);
    }

    public static final int NODEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeId_ = "";
    /**
     * <code>string nodeId = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string nodeId = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TERM_FIELD_NUMBER = 2;
    private long term_ = 0L;
    /**
     * <code>int64 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public long getTerm() {
      return term_;
    }

    public static final int AGREED_FIELD_NUMBER = 3;
    private boolean agreed_ = false;
    /**
     * <code>bool agreed = 3;</code>
     * @return The agreed.
     */
    @java.lang.Override
    public boolean getAgreed() {
      return agreed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeId_);
      }
      if (term_ != 0L) {
        output.writeInt64(2, term_);
      }
      if (agreed_ != false) {
        output.writeBool(3, agreed_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeId_);
      }
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, term_);
      }
      if (agreed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, agreed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.fengye.rpc.grpc.Grpc.ApplyVoteResponse)) {
        return super.equals(obj);
      }
      top.fengye.rpc.grpc.Grpc.ApplyVoteResponse other = (top.fengye.rpc.grpc.Grpc.ApplyVoteResponse) obj;

      if (!getNodeId()
          .equals(other.getNodeId())) return false;
      if (getTerm()
          != other.getTerm()) return false;
      if (getAgreed()
          != other.getAgreed()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODEID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + AGREED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAgreed());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.fengye.rpc.grpc.Grpc.ApplyVoteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.fengye.rpc.grpc.ApplyVoteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.fengye.rpc.grpc.ApplyVoteResponse)
        top.fengye.rpc.grpc.Grpc.ApplyVoteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.fengye.rpc.grpc.Grpc.ApplyVoteResponse.class, top.fengye.rpc.grpc.Grpc.ApplyVoteResponse.Builder.class);
      }

      // Construct using top.fengye.rpc.grpc.Grpc.ApplyVoteResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nodeId_ = "";
        term_ = 0L;
        agreed_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.fengye.rpc.grpc.Grpc.internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_descriptor;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.ApplyVoteResponse getDefaultInstanceForType() {
        return top.fengye.rpc.grpc.Grpc.ApplyVoteResponse.getDefaultInstance();
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.ApplyVoteResponse build() {
        top.fengye.rpc.grpc.Grpc.ApplyVoteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.Grpc.ApplyVoteResponse buildPartial() {
        top.fengye.rpc.grpc.Grpc.ApplyVoteResponse result = new top.fengye.rpc.grpc.Grpc.ApplyVoteResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.fengye.rpc.grpc.Grpc.ApplyVoteResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodeId_ = nodeId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.term_ = term_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.agreed_ = agreed_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.fengye.rpc.grpc.Grpc.ApplyVoteResponse) {
          return mergeFrom((top.fengye.rpc.grpc.Grpc.ApplyVoteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.fengye.rpc.grpc.Grpc.ApplyVoteResponse other) {
        if (other == top.fengye.rpc.grpc.Grpc.ApplyVoteResponse.getDefaultInstance()) return this;
        if (!other.getNodeId().isEmpty()) {
          nodeId_ = other.nodeId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getAgreed() != false) {
          setAgreed(other.getAgreed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                term_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                agreed_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeId_ = "";
      /**
       * <code>string nodeId = 1;</code>
       * @return The nodeId.
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return The bytes for nodeId.
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        nodeId_ = getDefaultInstance().getNodeId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nodeId = 1;</code>
       * @param value The bytes for nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long term_ ;
      /**
       * <code>int64 term = 2;</code>
       * @return The term.
       */
      @java.lang.Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>int64 term = 2;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 term = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        term_ = 0L;
        onChanged();
        return this;
      }

      private boolean agreed_ ;
      /**
       * <code>bool agreed = 3;</code>
       * @return The agreed.
       */
      @java.lang.Override
      public boolean getAgreed() {
        return agreed_;
      }
      /**
       * <code>bool agreed = 3;</code>
       * @param value The agreed to set.
       * @return This builder for chaining.
       */
      public Builder setAgreed(boolean value) {
        
        agreed_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool agreed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgreed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        agreed_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.fengye.rpc.grpc.ApplyVoteResponse)
    }

    // @@protoc_insertion_point(class_scope:top.fengye.rpc.grpc.ApplyVoteResponse)
    private static final top.fengye.rpc.grpc.Grpc.ApplyVoteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.fengye.rpc.grpc.Grpc.ApplyVoteResponse();
    }

    public static top.fengye.rpc.grpc.Grpc.ApplyVoteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplyVoteResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApplyVoteResponse>() {
      @java.lang.Override
      public ApplyVoteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApplyVoteResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApplyVoteResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.fengye.rpc.grpc.Grpc.ApplyVoteResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrpc.proto\022\023top.fengye.rpc.grpc\032\016bizPa" +
      "ram.proto\"U\n\024AppendEntriesRequest\022\016\n\006nod" +
      "eId\030\001 \001(\t\022-\n\007command\030\002 \001(\0132\034.top.fengye." +
      "rpc.grpc.Command\"\'\n\025AppendEntriesRespons" +
      "e\022\016\n\006nodeId\030\001 \001(\t\"0\n\020ApplyVoteRequest\022\016\n" +
      "\006nodeId\030\001 \001(\t\022\014\n\004term\030\002 \001(\003\"A\n\021ApplyVote" +
      "Response\022\016\n\006nodeId\030\001 \001(\t\022\014\n\004term\030\002 \001(\003\022\016" +
      "\n\006agreed\030\003 \001(\0102\312\001\n\004Raft\022f\n\rappendEntries" +
      "\022).top.fengye.rpc.grpc.AppendEntriesRequ" +
      "est\032*.top.fengye.rpc.grpc.AppendEntriesR" +
      "esponse\022Z\n\tapplyVote\022%.top.fengye.rpc.gr" +
      "pc.ApplyVoteRequest\032&.top.fengye.rpc.grp" +
      "c.ApplyVoteResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          top.fengye.rpc.grpc.BizParam.getDescriptor(),
        });
    internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fengye_rpc_grpc_AppendEntriesRequest_descriptor,
        new java.lang.String[] { "NodeId", "Command", });
    internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fengye_rpc_grpc_AppendEntriesResponse_descriptor,
        new java.lang.String[] { "NodeId", });
    internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fengye_rpc_grpc_ApplyVoteRequest_descriptor,
        new java.lang.String[] { "NodeId", "Term", });
    internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fengye_rpc_grpc_ApplyVoteResponse_descriptor,
        new java.lang.String[] { "NodeId", "Term", "Agreed", });
    top.fengye.rpc.grpc.BizParam.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
