// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bizParam.proto

package top.fengye.rpc.grpc;

public final class BizParam {
  private BizParam() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code top.fengye.rpc.grpc.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GET = 0;</code>
     */
    GET(0),
    /**
     * <code>PUT = 1;</code>
     */
    PUT(1),
    /**
     * <code>DEL = 2;</code>
     */
    DEL(2),
    /**
     * <code>NOOP = -1;</code>
     */
    NOOP(-1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GET = 0;</code>
     */
    public static final int GET_VALUE = 0;
    /**
     * <code>PUT = 1;</code>
     */
    public static final int PUT_VALUE = 1;
    /**
     * <code>DEL = 2;</code>
     */
    public static final int DEL_VALUE = 2;
    /**
     * <code>NOOP = -1;</code>
     */
    public static final int NOOP_VALUE = -1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return GET;
        case 1: return PUT;
        case 2: return DEL;
        case -1: return NOOP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.BizParam.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.fengye.rpc.grpc.CommandType)
  }

  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.fengye.rpc.grpc.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
     * @return The type.
     */
    top.fengye.rpc.grpc.BizParam.CommandType getType();

    /**
     * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
     * @return The key.
     */
    top.fengye.rpc.grpc.BizParam.Key getKey();
    /**
     * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
     */
    top.fengye.rpc.grpc.BizParam.KeyOrBuilder getKeyOrBuilder();

    /**
     * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
     * @return The value.
     */
    top.fengye.rpc.grpc.BizParam.Value getValue();
    /**
     * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
     */
    top.fengye.rpc.grpc.BizParam.ValueOrBuilder getValueOrBuilder();
  }
  /**
   * Protobuf type {@code top.fengye.rpc.grpc.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.fengye.rpc.grpc.Command)
      CommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Command();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Command_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fengye.rpc.grpc.BizParam.Command.class, top.fengye.rpc.grpc.BizParam.Command.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public top.fengye.rpc.grpc.BizParam.CommandType getType() {
      top.fengye.rpc.grpc.BizParam.CommandType result = top.fengye.rpc.grpc.BizParam.CommandType.forNumber(type_);
      return result == null ? top.fengye.rpc.grpc.BizParam.CommandType.UNRECOGNIZED : result;
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private top.fengye.rpc.grpc.BizParam.Key key_;
    /**
     * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return key_ != null;
    }
    /**
     * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.Key getKey() {
      return key_ == null ? top.fengye.rpc.grpc.BizParam.Key.getDefaultInstance() : key_;
    }
    /**
     * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
     */
    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.KeyOrBuilder getKeyOrBuilder() {
      return key_ == null ? top.fengye.rpc.grpc.BizParam.Key.getDefaultInstance() : key_;
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private top.fengye.rpc.grpc.BizParam.Value value_;
    /**
     * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return value_ != null;
    }
    /**
     * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
     * @return The value.
     */
    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.Value getValue() {
      return value_ == null ? top.fengye.rpc.grpc.BizParam.Value.getDefaultInstance() : value_;
    }
    /**
     * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
     */
    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.ValueOrBuilder getValueOrBuilder() {
      return value_ == null ? top.fengye.rpc.grpc.BizParam.Value.getDefaultInstance() : value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != top.fengye.rpc.grpc.BizParam.CommandType.GET.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (key_ != null) {
        output.writeMessage(2, getKey());
      }
      if (value_ != null) {
        output.writeMessage(3, getValue());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != top.fengye.rpc.grpc.BizParam.CommandType.GET.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (key_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getKey());
      }
      if (value_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.fengye.rpc.grpc.BizParam.Command)) {
        return super.equals(obj);
      }
      top.fengye.rpc.grpc.BizParam.Command other = (top.fengye.rpc.grpc.BizParam.Command) obj;

      if (type_ != other.type_) return false;
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.fengye.rpc.grpc.BizParam.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.fengye.rpc.grpc.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.fengye.rpc.grpc.Command)
        top.fengye.rpc.grpc.BizParam.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Command_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.fengye.rpc.grpc.BizParam.Command.class, top.fengye.rpc.grpc.BizParam.Command.Builder.class);
      }

      // Construct using top.fengye.rpc.grpc.BizParam.Command.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        key_ = null;
        if (keyBuilder_ != null) {
          keyBuilder_.dispose();
          keyBuilder_ = null;
        }
        value_ = null;
        if (valueBuilder_ != null) {
          valueBuilder_.dispose();
          valueBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Command_descriptor;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Command getDefaultInstanceForType() {
        return top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance();
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Command build() {
        top.fengye.rpc.grpc.BizParam.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Command buildPartial() {
        top.fengye.rpc.grpc.BizParam.Command result = new top.fengye.rpc.grpc.BizParam.Command(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.fengye.rpc.grpc.BizParam.Command result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.key_ = keyBuilder_ == null
              ? key_
              : keyBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.value_ = valueBuilder_ == null
              ? value_
              : valueBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.fengye.rpc.grpc.BizParam.Command) {
          return mergeFrom((top.fengye.rpc.grpc.BizParam.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.fengye.rpc.grpc.BizParam.Command other) {
        if (other == top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasKey()) {
          mergeKey(other.getKey());
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getKeyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getValueFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.CommandType getType() {
        top.fengye.rpc.grpc.BizParam.CommandType result = top.fengye.rpc.grpc.BizParam.CommandType.forNumber(type_);
        return result == null ? top.fengye.rpc.grpc.BizParam.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(top.fengye.rpc.grpc.BizParam.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.CommandType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private top.fengye.rpc.grpc.BizParam.Key key_;
      private com.google.protobuf.SingleFieldBuilderV3<
          top.fengye.rpc.grpc.BizParam.Key, top.fengye.rpc.grpc.BizParam.Key.Builder, top.fengye.rpc.grpc.BizParam.KeyOrBuilder> keyBuilder_;
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       * @return The key.
       */
      public top.fengye.rpc.grpc.BizParam.Key getKey() {
        if (keyBuilder_ == null) {
          return key_ == null ? top.fengye.rpc.grpc.BizParam.Key.getDefaultInstance() : key_;
        } else {
          return keyBuilder_.getMessage();
        }
      }
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       */
      public Builder setKey(top.fengye.rpc.grpc.BizParam.Key value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          key_ = value;
        } else {
          keyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       */
      public Builder setKey(
          top.fengye.rpc.grpc.BizParam.Key.Builder builderForValue) {
        if (keyBuilder_ == null) {
          key_ = builderForValue.build();
        } else {
          keyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       */
      public Builder mergeKey(top.fengye.rpc.grpc.BizParam.Key value) {
        if (keyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            key_ != null &&
            key_ != top.fengye.rpc.grpc.BizParam.Key.getDefaultInstance()) {
            getKeyBuilder().mergeFrom(value);
          } else {
            key_ = value;
          }
        } else {
          keyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = null;
        if (keyBuilder_ != null) {
          keyBuilder_.dispose();
          keyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       */
      public top.fengye.rpc.grpc.BizParam.Key.Builder getKeyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       */
      public top.fengye.rpc.grpc.BizParam.KeyOrBuilder getKeyOrBuilder() {
        if (keyBuilder_ != null) {
          return keyBuilder_.getMessageOrBuilder();
        } else {
          return key_ == null ?
              top.fengye.rpc.grpc.BizParam.Key.getDefaultInstance() : key_;
        }
      }
      /**
       * <code>.top.fengye.rpc.grpc.Key key = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.fengye.rpc.grpc.BizParam.Key, top.fengye.rpc.grpc.BizParam.Key.Builder, top.fengye.rpc.grpc.BizParam.KeyOrBuilder> 
          getKeyFieldBuilder() {
        if (keyBuilder_ == null) {
          keyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.fengye.rpc.grpc.BizParam.Key, top.fengye.rpc.grpc.BizParam.Key.Builder, top.fengye.rpc.grpc.BizParam.KeyOrBuilder>(
                  getKey(),
                  getParentForChildren(),
                  isClean());
          key_ = null;
        }
        return keyBuilder_;
      }

      private top.fengye.rpc.grpc.BizParam.Value value_;
      private com.google.protobuf.SingleFieldBuilderV3<
          top.fengye.rpc.grpc.BizParam.Value, top.fengye.rpc.grpc.BizParam.Value.Builder, top.fengye.rpc.grpc.BizParam.ValueOrBuilder> valueBuilder_;
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       * @return The value.
       */
      public top.fengye.rpc.grpc.BizParam.Value getValue() {
        if (valueBuilder_ == null) {
          return value_ == null ? top.fengye.rpc.grpc.BizParam.Value.getDefaultInstance() : value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       */
      public Builder setValue(top.fengye.rpc.grpc.BizParam.Value value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
        } else {
          valueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       */
      public Builder setValue(
          top.fengye.rpc.grpc.BizParam.Value.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       */
      public Builder mergeValue(top.fengye.rpc.grpc.BizParam.Value value) {
        if (valueBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            value_ != null &&
            value_ != top.fengye.rpc.grpc.BizParam.Value.getDefaultInstance()) {
            getValueBuilder().mergeFrom(value);
          } else {
            value_ = value;
          }
        } else {
          valueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = null;
        if (valueBuilder_ != null) {
          valueBuilder_.dispose();
          valueBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       */
      public top.fengye.rpc.grpc.BizParam.Value.Builder getValueBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       */
      public top.fengye.rpc.grpc.BizParam.ValueOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_ == null ?
              top.fengye.rpc.grpc.BizParam.Value.getDefaultInstance() : value_;
        }
      }
      /**
       * <code>.top.fengye.rpc.grpc.Value value = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.fengye.rpc.grpc.BizParam.Value, top.fengye.rpc.grpc.BizParam.Value.Builder, top.fengye.rpc.grpc.BizParam.ValueOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.fengye.rpc.grpc.BizParam.Value, top.fengye.rpc.grpc.BizParam.Value.Builder, top.fengye.rpc.grpc.BizParam.ValueOrBuilder>(
                  getValue(),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.fengye.rpc.grpc.Command)
    }

    // @@protoc_insertion_point(class_scope:top.fengye.rpc.grpc.Command)
    private static final top.fengye.rpc.grpc.BizParam.Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.fengye.rpc.grpc.BizParam.Command();
    }

    public static top.fengye.rpc.grpc.BizParam.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      @java.lang.Override
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.fengye.rpc.grpc.Key)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code top.fengye.rpc.grpc.Key}
   */
  public static final class Key extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.fengye.rpc.grpc.Key)
      KeyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Key.newBuilder() to construct.
    private Key(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Key() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Key();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Key_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Key_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fengye.rpc.grpc.BizParam.Key.class, top.fengye.rpc.grpc.BizParam.Key.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.fengye.rpc.grpc.BizParam.Key)) {
        return super.equals(obj);
      }
      top.fengye.rpc.grpc.BizParam.Key other = (top.fengye.rpc.grpc.BizParam.Key) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Key parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.fengye.rpc.grpc.BizParam.Key prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.fengye.rpc.grpc.Key}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.fengye.rpc.grpc.Key)
        top.fengye.rpc.grpc.BizParam.KeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Key_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Key_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.fengye.rpc.grpc.BizParam.Key.class, top.fengye.rpc.grpc.BizParam.Key.Builder.class);
      }

      // Construct using top.fengye.rpc.grpc.BizParam.Key.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Key_descriptor;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Key getDefaultInstanceForType() {
        return top.fengye.rpc.grpc.BizParam.Key.getDefaultInstance();
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Key build() {
        top.fengye.rpc.grpc.BizParam.Key result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Key buildPartial() {
        top.fengye.rpc.grpc.BizParam.Key result = new top.fengye.rpc.grpc.BizParam.Key(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.fengye.rpc.grpc.BizParam.Key result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = data_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.fengye.rpc.grpc.BizParam.Key) {
          return mergeFrom((top.fengye.rpc.grpc.BizParam.Key)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.fengye.rpc.grpc.BizParam.Key other) {
        if (other == top.fengye.rpc.grpc.BizParam.Key.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.fengye.rpc.grpc.Key)
    }

    // @@protoc_insertion_point(class_scope:top.fengye.rpc.grpc.Key)
    private static final top.fengye.rpc.grpc.BizParam.Key DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.fengye.rpc.grpc.BizParam.Key();
    }

    public static top.fengye.rpc.grpc.BizParam.Key getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Key>
        PARSER = new com.google.protobuf.AbstractParser<Key>() {
      @java.lang.Override
      public Key parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Key> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Key> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.Key getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.fengye.rpc.grpc.Value)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code top.fengye.rpc.grpc.Value}
   */
  public static final class Value extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.fengye.rpc.grpc.Value)
      ValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Value.newBuilder() to construct.
    private Value(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Value() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Value();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Value_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fengye.rpc.grpc.BizParam.Value.class, top.fengye.rpc.grpc.BizParam.Value.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.fengye.rpc.grpc.BizParam.Value)) {
        return super.equals(obj);
      }
      top.fengye.rpc.grpc.BizParam.Value other = (top.fengye.rpc.grpc.BizParam.Value) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.fengye.rpc.grpc.BizParam.Value prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.fengye.rpc.grpc.Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.fengye.rpc.grpc.Value)
        top.fengye.rpc.grpc.BizParam.ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Value_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.fengye.rpc.grpc.BizParam.Value.class, top.fengye.rpc.grpc.BizParam.Value.Builder.class);
      }

      // Construct using top.fengye.rpc.grpc.BizParam.Value.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_Value_descriptor;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Value getDefaultInstanceForType() {
        return top.fengye.rpc.grpc.BizParam.Value.getDefaultInstance();
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Value build() {
        top.fengye.rpc.grpc.BizParam.Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.Value buildPartial() {
        top.fengye.rpc.grpc.BizParam.Value result = new top.fengye.rpc.grpc.BizParam.Value(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.fengye.rpc.grpc.BizParam.Value result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = data_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.fengye.rpc.grpc.BizParam.Value) {
          return mergeFrom((top.fengye.rpc.grpc.BizParam.Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.fengye.rpc.grpc.BizParam.Value other) {
        if (other == top.fengye.rpc.grpc.BizParam.Value.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.fengye.rpc.grpc.Value)
    }

    // @@protoc_insertion_point(class_scope:top.fengye.rpc.grpc.Value)
    private static final top.fengye.rpc.grpc.BizParam.Value DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.fengye.rpc.grpc.BizParam.Value();
    }

    public static top.fengye.rpc.grpc.BizParam.Value getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Value>
        PARSER = new com.google.protobuf.AbstractParser<Value>() {
      @java.lang.Override
      public Value parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Value> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Value> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.Value getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.fengye.rpc.grpc.LogEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <code>int32 term = 2;</code>
     * @return The term.
     */
    int getTerm();

    /**
     * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
     * @return Whether the command field is set.
     */
    boolean hasCommand();
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
     * @return The command.
     */
    top.fengye.rpc.grpc.BizParam.Command getCommand();
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
     */
    top.fengye.rpc.grpc.BizParam.CommandOrBuilder getCommandOrBuilder();
  }
  /**
   * Protobuf type {@code top.fengye.rpc.grpc.LogEntry}
   */
  public static final class LogEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:top.fengye.rpc.grpc.LogEntry)
      LogEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogEntry.newBuilder() to construct.
    private LogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogEntry() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogEntry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_LogEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_LogEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.fengye.rpc.grpc.BizParam.LogEntry.class, top.fengye.rpc.grpc.BizParam.LogEntry.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_ = 0;
    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }

    public static final int TERM_FIELD_NUMBER = 2;
    private int term_ = 0;
    /**
     * <code>int32 term = 2;</code>
     * @return The term.
     */
    @java.lang.Override
    public int getTerm() {
      return term_;
    }

    public static final int COMMAND_FIELD_NUMBER = 3;
    private top.fengye.rpc.grpc.BizParam.Command command_;
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
     * @return Whether the command field is set.
     */
    @java.lang.Override
    public boolean hasCommand() {
      return command_ != null;
    }
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
     * @return The command.
     */
    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.Command getCommand() {
      return command_ == null ? top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance() : command_;
    }
    /**
     * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
     */
    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.CommandOrBuilder getCommandOrBuilder() {
      return command_ == null ? top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance() : command_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeInt32(1, index_);
      }
      if (term_ != 0) {
        output.writeInt32(2, term_);
      }
      if (command_ != null) {
        output.writeMessage(3, getCommand());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (term_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, term_);
      }
      if (command_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCommand());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.fengye.rpc.grpc.BizParam.LogEntry)) {
        return super.equals(obj);
      }
      top.fengye.rpc.grpc.BizParam.LogEntry other = (top.fengye.rpc.grpc.BizParam.LogEntry) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (getTerm()
          != other.getTerm()) return false;
      if (hasCommand() != other.hasCommand()) return false;
      if (hasCommand()) {
        if (!getCommand()
            .equals(other.getCommand())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + getTerm();
      if (hasCommand()) {
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getCommand().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.fengye.rpc.grpc.BizParam.LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.fengye.rpc.grpc.BizParam.LogEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code top.fengye.rpc.grpc.LogEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:top.fengye.rpc.grpc.LogEntry)
        top.fengye.rpc.grpc.BizParam.LogEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_LogEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_LogEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.fengye.rpc.grpc.BizParam.LogEntry.class, top.fengye.rpc.grpc.BizParam.LogEntry.Builder.class);
      }

      // Construct using top.fengye.rpc.grpc.BizParam.LogEntry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        index_ = 0;
        term_ = 0;
        command_ = null;
        if (commandBuilder_ != null) {
          commandBuilder_.dispose();
          commandBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.fengye.rpc.grpc.BizParam.internal_static_top_fengye_rpc_grpc_LogEntry_descriptor;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.LogEntry getDefaultInstanceForType() {
        return top.fengye.rpc.grpc.BizParam.LogEntry.getDefaultInstance();
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.LogEntry build() {
        top.fengye.rpc.grpc.BizParam.LogEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.fengye.rpc.grpc.BizParam.LogEntry buildPartial() {
        top.fengye.rpc.grpc.BizParam.LogEntry result = new top.fengye.rpc.grpc.BizParam.LogEntry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(top.fengye.rpc.grpc.BizParam.LogEntry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.index_ = index_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.term_ = term_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.command_ = commandBuilder_ == null
              ? command_
              : commandBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.fengye.rpc.grpc.BizParam.LogEntry) {
          return mergeFrom((top.fengye.rpc.grpc.BizParam.LogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.fengye.rpc.grpc.BizParam.LogEntry other) {
        if (other == top.fengye.rpc.grpc.BizParam.LogEntry.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getTerm() != 0) {
          setTerm(other.getTerm());
        }
        if (other.hasCommand()) {
          mergeCommand(other.getCommand());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                index_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                term_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getCommandFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int index_ ;
      /**
       * <code>int32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }
      /**
       * <code>int32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0;
        onChanged();
        return this;
      }

      private int term_ ;
      /**
       * <code>int32 term = 2;</code>
       * @return The term.
       */
      @java.lang.Override
      public int getTerm() {
        return term_;
      }
      /**
       * <code>int32 term = 2;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(int value) {
        
        term_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 term = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        term_ = 0;
        onChanged();
        return this;
      }

      private top.fengye.rpc.grpc.BizParam.Command command_;
      private com.google.protobuf.SingleFieldBuilderV3<
          top.fengye.rpc.grpc.BizParam.Command, top.fengye.rpc.grpc.BizParam.Command.Builder, top.fengye.rpc.grpc.BizParam.CommandOrBuilder> commandBuilder_;
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       * @return Whether the command field is set.
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       * @return The command.
       */
      public top.fengye.rpc.grpc.BizParam.Command getCommand() {
        if (commandBuilder_ == null) {
          return command_ == null ? top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance() : command_;
        } else {
          return commandBuilder_.getMessage();
        }
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       */
      public Builder setCommand(top.fengye.rpc.grpc.BizParam.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
        } else {
          commandBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       */
      public Builder setCommand(
          top.fengye.rpc.grpc.BizParam.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          command_ = builderForValue.build();
        } else {
          commandBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       */
      public Builder mergeCommand(top.fengye.rpc.grpc.BizParam.Command value) {
        if (commandBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            command_ != null &&
            command_ != top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance()) {
            getCommandBuilder().mergeFrom(value);
          } else {
            command_ = value;
          }
        } else {
          commandBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000004);
        command_ = null;
        if (commandBuilder_ != null) {
          commandBuilder_.dispose();
          commandBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       */
      public top.fengye.rpc.grpc.BizParam.Command.Builder getCommandBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       */
      public top.fengye.rpc.grpc.BizParam.CommandOrBuilder getCommandOrBuilder() {
        if (commandBuilder_ != null) {
          return commandBuilder_.getMessageOrBuilder();
        } else {
          return command_ == null ?
              top.fengye.rpc.grpc.BizParam.Command.getDefaultInstance() : command_;
        }
      }
      /**
       * <code>.top.fengye.rpc.grpc.Command command = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          top.fengye.rpc.grpc.BizParam.Command, top.fengye.rpc.grpc.BizParam.Command.Builder, top.fengye.rpc.grpc.BizParam.CommandOrBuilder> 
          getCommandFieldBuilder() {
        if (commandBuilder_ == null) {
          commandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              top.fengye.rpc.grpc.BizParam.Command, top.fengye.rpc.grpc.BizParam.Command.Builder, top.fengye.rpc.grpc.BizParam.CommandOrBuilder>(
                  getCommand(),
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        return commandBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:top.fengye.rpc.grpc.LogEntry)
    }

    // @@protoc_insertion_point(class_scope:top.fengye.rpc.grpc.LogEntry)
    private static final top.fengye.rpc.grpc.BizParam.LogEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.fengye.rpc.grpc.BizParam.LogEntry();
    }

    public static top.fengye.rpc.grpc.BizParam.LogEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogEntry>
        PARSER = new com.google.protobuf.AbstractParser<LogEntry>() {
      @java.lang.Override
      public LogEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LogEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.fengye.rpc.grpc.BizParam.LogEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fengye_rpc_grpc_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fengye_rpc_grpc_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fengye_rpc_grpc_Key_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fengye_rpc_grpc_Key_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fengye_rpc_grpc_Value_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fengye_rpc_grpc_Value_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_fengye_rpc_grpc_LogEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_fengye_rpc_grpc_LogEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016bizParam.proto\022\023top.fengye.rpc.grpc\"\213\001" +
      "\n\007Command\022.\n\004type\030\001 \001(\0162 .top.fengye.rpc" +
      ".grpc.CommandType\022%\n\003key\030\002 \001(\0132\030.top.fen" +
      "gye.rpc.grpc.Key\022)\n\005value\030\003 \001(\0132\032.top.fe" +
      "ngye.rpc.grpc.Value\"\023\n\003Key\022\014\n\004data\030\001 \001(\014" +
      "\"\025\n\005Value\022\014\n\004data\030\001 \001(\014\"V\n\010LogEntry\022\r\n\005i" +
      "ndex\030\001 \001(\005\022\014\n\004term\030\002 \001(\005\022-\n\007command\030\003 \001(" +
      "\0132\034.top.fengye.rpc.grpc.Command*;\n\013Comma" +
      "ndType\022\007\n\003GET\020\000\022\007\n\003PUT\020\001\022\007\n\003DEL\020\002\022\021\n\004NOO" +
      "P\020\377\377\377\377\377\377\377\377\377\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_top_fengye_rpc_grpc_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_fengye_rpc_grpc_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fengye_rpc_grpc_Command_descriptor,
        new java.lang.String[] { "Type", "Key", "Value", });
    internal_static_top_fengye_rpc_grpc_Key_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_top_fengye_rpc_grpc_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fengye_rpc_grpc_Key_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_top_fengye_rpc_grpc_Value_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_top_fengye_rpc_grpc_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fengye_rpc_grpc_Value_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_top_fengye_rpc_grpc_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_top_fengye_rpc_grpc_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_fengye_rpc_grpc_LogEntry_descriptor,
        new java.lang.String[] { "Index", "Term", "Command", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
